### ISSUE TITLE
Upgrade airbrake

### ISSUE THREAD

**Issue by Exelord** [201-created/ember-cli-airbrake#22]
Hi :)
Do you intend to continue maintenance of this package?
We should upgrade airbrake client and we can also move it to from bower to npm.

**Comment by Exelord** [comment]
ping :)

**Comment by mileslane** [comment]
ping 2

**Comment by vihai** [comment]
Yeah ping :)

**Comment by mixonic** [comment]
The airbrake lib was moved to NPM in https://github.com/201-created/ember-cli-airbrake/commit/8a277a16588ddce53851c02b5921aa0cc32e26c4 a year ago.

This issue seems to not be looking for anything in particular or actionable, so I'm going to close it. Please feel free to open PRs and other issues!

**Comment by vihai** [comment]
Yes, the dependency is now via npm, however ember-cli-airbrake isn't able to use current airbrake-js npm as it requires some fix (setHost is not present anymore).
